# Generated by Django 4.2.8 on 2024-05-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0001_initial'),
        ('saving', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_deposit_products',
            field=models.ManyToManyField(blank=True, related_name='liked_by_users', to='deposit.depositproductsbaseinfo'),
        ),
        migrations.AddField(
            model_name='user',
            name='liked_fixed_saving_products',
            field=models.ManyToManyField(blank=True, related_name='liked_by_users_fixed', to='saving.fixedsavingproductsbaseinfo'),
        ),
        migrations.AddField(
            model_name='user',
            name='liked_free_saving_products',
            field=models.ManyToManyField(blank=True, related_name='liked_by_users_free', to='saving.freesavingproductsbaseinfo'),
        ),
    ]
