# Generated by Django 4.2.8 on 2024-05-16 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositProductsBaseInfo',
            fields=[
                ('base_product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fin_co_no', models.CharField(max_length=8)),
                ('kor_co_nm', models.CharField(max_length=255)),
                ('fin_prdt_cd', models.CharField(max_length=15)),
                ('fin_prdt_nm', models.CharField(max_length=255)),
                ('join_way', models.CharField(max_length=255)),
                ('mtrt_int', models.TextField()),
                ('spcl_cnd', models.TextField()),
                ('join_deny', models.CharField(max_length=1)),
                ('join_member', models.CharField(max_length=255)),
                ('etc_note', models.CharField(max_length=255)),
                ('max_limit', models.BigIntegerField(blank=True, null=True)),
                ('dcls_strt_day', models.CharField(blank=True, max_length=8, null=True)),
                ('dcls_end_day', models.CharField(blank=True, max_length=8, null=True)),
                ('fin_co_subm_day', models.CharField(blank=True, max_length=14, null=True)),
            ],
            options={
                'db_table': 'DepositProductsBaseInfo',
            },
        ),
        migrations.CreateModel(
            name='DepositProductsOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_co_no', models.CharField(max_length=8)),
                ('fin_prdt_cd', models.CharField(max_length=20)),
                ('intr_rate_type', models.CharField(max_length=1)),
                ('intr_rate_type_nm', models.CharField(max_length=10)),
                ('save_trm', models.CharField(max_length=2)),
                ('intr_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('intr_rate2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='deposit.depositproductsbaseinfo')),
            ],
            options={
                'db_table': 'DepositProductsOption',
                'unique_together': {('fin_co_no', 'fin_prdt_cd', 'intr_rate_type', 'intr_rate_type_nm', 'save_trm')},
            },
        ),
    ]
