# Generated by Django 4.2.8 on 2024-05-17 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositproductsbaseinfo',
            name='base_product_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='기본 상품 ID'),
        ),
        migrations.AlterField(
            model_name='depositproductsbaseinfo',
            name='dcls_end_day',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='공시 종료일'),
        ),
        migrations.AlterField(
            model_name='depositproductsbaseinfo',
            name='dcls_strt_day',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='공시 시작일'),
        ),
        migrations.AlterField(
            model_name='depositproductsbaseinfo',
            name='etc_note',
            field=models.CharField(max_length=255, verbose_name='기타 유의사항'),
        ),
        migrations.AlterField(
            model_name='depositproductsbaseinfo',
            name='fin_co_no',
            field=models.CharField(max_length=8, verbose_name='금융회사 코드'),
        ),
        migrations.AlterField(
            model_name='depositproductsbaseinfo',
            name='fin_co_subm_day',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='금융회사 제출일'),
        ),
        migrations.AlterField(
            model_name='depositproductsbaseinfo',
            name='fin_prdt_cd',
            field=models.CharField(max_length=15, verbose_name='금융상품 코드'),
        ),
        migrations.AlterField(
            model_name='depositproductsbaseinfo',
            name='fin_prdt_nm',
            field=models.CharField(max_length=255, verbose_name='금융 상품명'),
        ),
        migrations.AlterField(
            model_name='depositproductsbaseinfo',
            name='join_deny',
            field=models.CharField(max_length=1, verbose_name='가입제한'),
        ),
        migrations.AlterField(
            model_name='depositproductsbaseinfo',
            name='join_member',
            field=models.CharField(max_length=255, verbose_name='가입대상'),
        ),
        migrations.AlterField(
            model_name='depositproductsbaseinfo',
            name='join_way',
            field=models.CharField(max_length=255, verbose_name='가입 방법'),
        ),
        migrations.AlterField(
            model_name='depositproductsbaseinfo',
            name='kor_co_nm',
            field=models.CharField(max_length=255, verbose_name='금융회사 명'),
        ),
        migrations.AlterField(
            model_name='depositproductsbaseinfo',
            name='max_limit',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='최고한도'),
        ),
        migrations.AlterField(
            model_name='depositproductsbaseinfo',
            name='mtrt_int',
            field=models.TextField(verbose_name='만기 후 이자율'),
        ),
        migrations.AlterField(
            model_name='depositproductsbaseinfo',
            name='spcl_cnd',
            field=models.TextField(verbose_name='우대조건'),
        ),
        migrations.AlterField(
            model_name='depositproductsoption',
            name='base_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='deposit.depositproductsbaseinfo', verbose_name='기본 상품'),
        ),
        migrations.AlterField(
            model_name='depositproductsoption',
            name='fin_co_no',
            field=models.CharField(max_length=8, verbose_name='금융회사 코드'),
        ),
        migrations.AlterField(
            model_name='depositproductsoption',
            name='fin_prdt_cd',
            field=models.CharField(max_length=20, verbose_name='금융상품 코드'),
        ),
        migrations.AlterField(
            model_name='depositproductsoption',
            name='intr_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='저축 금리'),
        ),
        migrations.AlterField(
            model_name='depositproductsoption',
            name='intr_rate2',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='최고 우대금리'),
        ),
        migrations.AlterField(
            model_name='depositproductsoption',
            name='intr_rate_type',
            field=models.CharField(max_length=1, verbose_name='저축 금리 유형'),
        ),
        migrations.AlterField(
            model_name='depositproductsoption',
            name='intr_rate_type_nm',
            field=models.CharField(max_length=10, verbose_name='저축 금리 유형명'),
        ),
        migrations.AlterField(
            model_name='depositproductsoption',
            name='save_trm',
            field=models.CharField(max_length=2, verbose_name='저축 기간'),
        ),
    ]
