# Generated by Django 4.2.8 on 2024-05-18 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depositproductsbaseinfo',
            options={'verbose_name': '예금 상품 기본 정보'},
        ),
        migrations.AlterModelOptions(
            name='depositproductsoption',
            options={'verbose_name': '예금 상품 옵션'},
        ),
    ]
